######################################################
###           Configuration file for               ###
### Bioinformatics Reference Data Manager (BRDM)   ###
######################################################

#root_folder: "/start/folder/for/reference/data/"
root_folder: "../out/real_test/"
backup_folder: "../out/real_test/backup/"

### Name of the BRDM-specific readme file. This file is automatically placed in every folder with data and has dual use:
### for user reference and for backup.
readme_file: "README+"

### Number of times BRDM will re-triy failed download and failed connections
download_retry_num: 3
connection_retry_num: 3


######################################################
### Setup, specific for each download module       ###
######################################################

ncbi:
    destination_folder: "ncbi/"

    blast_db:
        destination_folder: "blast/"
        ftp: "ftp.ncbi.nlm.nih.gov"
        ftp_dir: "blast/db/"
        user: "anonymous"
        password: "anonymous"
        info_file_name: "README"



######################################################
###                 Logging                        ###
######################################################
## Keep below structure - this format is expected by python's logging module
logging:

    version: 1
    disable_existing_loggers: true

    formatters:
        briefFormatter:
            format: '%(levelname)s: %(message)s'
        preciseFormatter:
            format: '%(asctime)s - %(module)s - %(levelname)s: %(message)s'
            datefmt: '%Y/%m/%d %H:%M:%S'

    handlers:
        console:
            class: logging.StreamHandler
            formatter: briefFormatter
            level: ERROR
            stream: ext://sys.stdout
        file:
            class : logging.FileHandler
            formatter: preciseFormatter
            level: DEBUG
            filename: reference_data_manager.log

    root:
        level: DEBUG
        handlers: [console, file]